version: "3.8"
services:
  transaction-reconciliation-backend:
    build: .
    restart: on-failure
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORTó
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true