openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
- url: http://localhost:8080
  description: Generated server url
paths:
  /transaction-reconciliation:
    post:
      tags:
      - reconciliation-controller
      operationId: perform
      responses:
        "400":
          description: Bad Request
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Errors'
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: object
components:
  schemas:
    Errors:
      type: object
      properties:
        errors:
          type: array
          items:
            type: string
